user: '{{ ansible_env.SUDO_USER }}'

oh_my_zsh:
  theme: gentoo
  plugins:
    debian:
      - debian
      - git
      - command-not-found
    redhat:
      - git
      - yum

user_home: /home/{{ user }}
zshrc: "{{ user_home }}/.zshrc"
